### ISSUE TITLE
Handle remote imports, first without sanity checks

### ISSUE THREAD

**Issue by Nadrieril** [Nadrieril/dhall-rust#10]
Dhall supports importing from remote URLs. This is slightly tricky to support because remote imports can themselves import relative files. The standard gives details on how this should work: https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#chaining-imports (feel free to ignore the thing about canonicalizing directories for now).
Headers, CORS headers and referential sanity check are out of scope for now.

**Comment by FintanH** [comment]
Why are headers defined as `ImportHashed` (https://github.com/Nadrieril/dhall-rust/blob/master/dhall_syntax/src/core/import.rs#L29) ? :thinking: 

Are those not supposed to be HTTP headers?

**Comment by Nadrieril** [comment]
The headers are specified by another import; see here for example: https://hackage.haskell.org/package/dhall-1.25.0/docs/Dhall-Tutorial.html#g:15 .
Note that this behavior has changed in the standard since https://github.com/dhall-lang/dhall-lang/pull/560, but we haven't caught up with that yet.

**Comment by FintanH** [comment]
Ah of course! I never used the feature so wasn't that familiar with it :grin: I'm trying to work on remote imports at the moment. Let's see how it goes :crossed_fingers:

**Comment by Nadrieril** [comment]
Actually, I am catching up to the inline headers feature, so please ignore headers for now, as the code around them will change
