### ISSUE TITLE
Support for dhall serializer

### ISSUE THREAD

**Issue by rlecomte** [Nadrieril/dhall-rust#164]
Do you plan to implement dhall serialization as It have been [define](https://github.com/dhall-lang/dhall-lang/pull/194)?

Thank you for giving your time on this implementation by the way

**Comment by Nadrieril** [comment]
Dhall serialization into CBOR is implemented, because it's needed for the semantic cache. I'm not planning on making it accessible in the serde_dhall api however. Do you have a usecase in mind for it ?

**Comment by rlecomte** [comment]
Sure! I would like to print the loaded dhall configuration on a web endpoint. I could use JSON instead but if there isn't any technical issue for doing that, why don't use dhall?

**Comment by Nadrieril** [comment]
Oh, do you mean printing the dhall value as text then ? That would make more sense in the api, I could support that

**Comment by rlecomte** [comment]
It would be great!

**Comment by Nadrieril** [comment]
I've started working on this, but won't have time to finish it just yet. It'll get done eventually but I can't promise a timeline
