### ISSUE TITLE
Make reqwest an optional dependency

### ISSUE THREAD

**Issue by myfreeweb** [Nadrieril/dhall-rust#169]
Even on desktop platforms, it would be useful to be able to disable the web download stuff completely using a cargo feature.

**Comment by Nadrieril** [comment]
Is it because the dependency is painful, or is it from a security perspective that you'd rather not allow remote imports?
If it's the latter, I had planned to add an option to disable or whitelist remote imports to the Deserializer interface. Would that solve your problem?

**Comment by myfreeweb** [comment]
It's both, really.

**Comment by Nadrieril** [comment]
I guess it's not unreasonable because reqwest pulls in many things. But that won't be at the top of my priority list

**Comment by Nadrieril** [comment]
I discovered https://docs.rs/attohttpc/0.14.0/attohttpc/ , which is much lighter than reqwest and seems like it would do the job nicely. I wouldn't mind using that instead, it might even work under wasm

**Comment by Nadrieril** [comment]
Nope, it doesn't work under wasm. Since I eventually need async imports in order to get remote imports under wasm, I have to stay with reqwest :(
