### ISSUE TITLE
Support Dhall version 18.0.0

### ISSUE THREAD

**Issue by rushsteve1** [Nadrieril/dhall-rust#175]
As of dhall-lang/dhall-lang commit `4ecd748e574df6b3e568090077042d184298a7e4` Dhall is now on version 18.0.0.
According to [the changelog](https://github.com/dhall-lang/dhall-lang/blob/master/CHANGELOG.md#v1800) this is a seemingly minor update with a enhancement to the `with` expression, though it is a breaking change.

**Comment by Nadrieril** [comment]
It's minor from the end-user's perspective, but changes a few things for implementors. But it wasn't that hard: https://github.com/Nadrieril/dhall-rust/pull/176
