### ISSUE TITLE
abnf to pest issues

### ISSUE THREAD

**Issue by letto4135** [Nadrieril/dhall-rust#241]
This is an oasis odata abnf
https://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/abnf/odata-abnf-construction-rules.txt

using the example for how to use abnf to pest crate it errors almost instantly once it is past the comments at the beginning, and I don't know enough about abnf or pest to know why, but thought you might.

```
called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "0: at line 105, in Eof:\nodataRelativeUri = '$batch'                           ; Note: case-sensitive!\n^\n\n" }
```

Ultimately I was trying to convert this abnf to antlr then to Golang, but found this and thought I'd try it out.

**Comment by Nadrieril** [comment]
I'm using the [abnf](https://github.com/duesee/abnf) crate to parse abnf files, the error comes from them. I don't know much more, you might want to ask over there. Neither this nor them is maintained much though
