### ISSUE TITLE
Canonicalization of imports

### ISSUE THREAD

**Issue by basile-henry** [Nadrieril/dhall-rust#76]
PRs #68 and #75 were implemented relying on equivalent imports being equal or hashing to the same value. Unfortunately that is not the case and we should implement the canonicalization of imports as described [in the standard](https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#canonicalization-of-imports).

**Comment by Nadrieril** [comment]
Completely agreed :) I hoped we could just ignore this for a while but apparently we can't

**Comment by basile-henry** [comment]
It can probably wait a little while longer, but we won't get import caching or import cycle detection (though I guess we're bound to find cycles even if it's only after two "loops") for some imports. Canonicalization only really matters when using relative paths in imports I think.

**Comment by FintanH** [comment]
I've been taking a crack at this :)

**Comment by FintanH** [comment]
@Nadrieril I was thinking of organising the `import` stuff to be closer to the [description given by dhall-lang](https://github.com/dhall-lang/dhall-lang/blob/master/standard/imports.md#directories-and-files). So I've structured things like:

```rust
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Directory {
    pub components: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct File {
    pub directory: Directory,
    pub file: String,
}
```

But this is gonna break parser code, which looks like black magic to me :sweat_smile: Any advice to proceed? Are you ok with this type of change?

**Comment by FintanH** [comment]
Actually I was going about the parser the wrong way. I eventually understood what it was up to (cool stuff!). 

The question still stands on the above structuring though :)

**Comment by Nadrieril** [comment]
Hmm, I'm not sure about that one. A month ago I would have said yes, but since then an effort has been made to make dhall use standard URL semantics: https://github.com/dhall-lang/dhall-lang/issues/581 . So my hope is that using the standard rust Path utilities should do exactly what the dhall spec wants.
Knowing that, I'll let you decide what seems sensible to you, since I never read the import semantics in detail. Feel free to do the above structuring then :)
Also, glad you managed to make some sense out of the parser code ^^'

**Comment by FintanH** [comment]
Oh thanks for the pointers. I'll read through those semantics. I dunno much about the RFC in question so it'll take me some reading to get up to speed.

I actually have working code using the above structure, but need to complete the canonicalization code and test it. I'll hold off on that until I understand the above :)

**Comment by Nadrieril** [comment]
@FintanH How's it looking ? It's fine to just implement whatever, and let future users find the mistakes; don't bore yourself over that RFC.

**Comment by FintanH** [comment]
@Nadrieril thanks for checking in. I haven't had the chance to get going on this again. I might have some time this weekend :) I'll just finish the canonicalization stuff with what I have and can see what you think :grin:
